language: php
php:
- '7.2'
- '7.3'
- '7.4snapshot'

before_script:
  - composer install -o --prefer-dist
script:
  - vendor/bin/phpunit --testsuite=unit
  - vendor/bin/phpunit --testsuite=integration
