controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
index:
    path: /
    methods: GET
    controller: App\Controller\IndexController::index

get_categories:
    path: /categories
    methods: GET
    controller: App\Controller\CategoryController::getCategories

get_products:
    path: /products
    methods: GET
    defaults:
        _controller: App\Controller\ProductController::getProducts
