version: '3.8'

services:
  php-datadog:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.datadog
    volumes:
      - .:/var/www/symfony
    expose:
      - "9000"
    environment:
      - DD_SERVICE=symfony-app
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_API_KEY=${DD_API_KEY}
      - DD_TRACE_DEBUG=true
      - DD_LOGS_ENABLED=true  
      - DD_PROCESS_AGENT_ENABLED=true

#  php-newrelic:
#    build:
#      context: ./docker/php
#      dockerfile: Dockerfile.newrelic
#      args:
#        NEWRELIC_KEY: ${NEWRELIC_KEY}
#        NEWRELIC_APP_NAME: "PHP_SDK"
#    volumes:
#      - .:/var/www/symfony
#    expose:
#      - "9001"

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - php-datadog
#      - php-newrelic
    volumes:
      - ./var/logs/nginx:/var/log/nginx
      - .:/var/www/symfony

  datadog-agent:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_APM_ENABLED=true
    ports:
      - "8126:8126/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/proc/:/host/proc/:ro"
      - "/sys/fs/cgroup/:/host/sys/fs/cgroup:ro"

